# Generated by Django 4.2.5 on 2023-11-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('función', models.TextField()),
                ('preocupaciones', models.TextField()),
                ('propiedades_dermatologicas', models.TextField()),
                ('toxicidad', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('urlImagen', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('sostenibilidad', models.CharField(blank=True, max_length=255, null=True)),
                ('urlImagen', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
